---
dependencies:
- name: spark
  version: ~1.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: spark.enabled
- name: superset
  version: ~1.1.6
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: superset.enabled
- name: postgresql
  version: ~5.3.10
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: minio
  version: ~2.4.16
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
- name: grafana
  version: ~3.5.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: grafana.enabled
- name: jupyterhub
  version: ~0.8.0
  repository: https://jupyterhub.github.io/helm-chart/
  condition: jupyterhub.enabled
- name: nifi
  version: ~0.1.0
  repository: https://cetic.github.io/helm-charts/
  condition: nifi.enabled
- name: pgadmin
  version: ~0.1.2
  repository: https://cetic.github.io/helm-charts/
  condition: pgadmin.enabled
